program T2Ti_ServidorAplicacao;

uses
  FastMM4,
  FastMM4Messages,
  Forms,
  SA in 'SA.pas' {FSA},
  Controller in 'Controller.pas',
  DSServerClass in 'DSServerClass.pas',
  Constantes in '..\Comum\Constantes.pas',
  Biblioteca in '..\Comum\Biblioteca.pas',
  SessaoUsuario in 'SessaoUsuario.pas',
  Atributos in '..\Comum\Atributos.pas',
  UDataModule in 'UDataModule.pas' {FDataModule: TDataModule},
  T2TiORM in '..\Comum\T2TiORM.pas',
  UDataModuleConexao in '..\Comum\DataModule\UDataModuleConexao.pas' {FDataModuleConexao: TDataModule},
  VO in '..\Comum\VO\VO.pas',
  FuncaoVO in '..\Comum\VO\FuncaoVO.pas',
  PapelFuncaoVO in '..\Comum\VO\PapelFuncaoVO.pas',
  PapelVO in '..\Comum\VO\PapelVO.pas',
  UsuarioVO in '..\Comum\VO\UsuarioVO.pas',
  AtividadeForCliVO in '..\Comum\VO\AtividadeForCliVO.pas',
  CargoVO in '..\Comum\VO\CargoVO.pas',
  CepVO in '..\Comum\VO\CepVO.pas',
  ColaboradorVO in '..\Comum\VO\ColaboradorVO.pas',
  ContadorVO in '..\Comum\VO\ContadorVO.pas',
  PaisVO in '..\Comum\VO\PaisVO.pas',
  PessoaFisicaVO in '..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\Comum\VO\PessoaJuridicaVO.pas',
  PessoaVO in '..\Comum\VO\PessoaVO.pas',
  SituacaoColaboradorVO in '..\Comum\VO\SituacaoColaboradorVO.pas',
  SituacaoForCliVO in '..\Comum\VO\SituacaoForCliVO.pas',
  TipoAdmissaoVO in '..\Comum\VO\TipoAdmissaoVO.pas',
  TipoColaboradorVO in '..\Comum\VO\TipoColaboradorVO.pas',
  UfVO in '..\Comum\VO\UfVO.pas',
  ProdutoVO in '..\Comum\VO\ProdutoVO.pas',
  UnidadeProdutoVO in '..\Comum\VO\UnidadeProdutoVO.pas',
  TributGrupoTributarioVO in '..\Comum\VO\TributGrupoTributarioVO.pas',
  AlmoxarifadoVO in '..\Comum\VO\AlmoxarifadoVO.pas',
  AdministrativoFormularioVO in '..\Comum\VO\AdministrativoFormularioVO.pas',
  ViewSessaoEmpresaVO in '..\Comum\VO\ViewSessaoEmpresaVO.pas',
  ProdutoMarcaVO in '..\Comum\VO\ProdutoMarcaVO.pas',
  ProdutoSubGrupoVO in '..\Comum\VO\ProdutoSubGrupoVO.pas',
  ProdutoGrupoVO in '..\Comum\VO\ProdutoGrupoVO.pas',
  ProdutoLoteVO in '..\Comum\VO\ProdutoLoteVO.pas',
  NfeTransporteVolumeVO in '..\Comum\VO\NfeTransporteVolumeVO.pas',
  NfeCanaDeducoesSafraVO in '..\Comum\VO\NfeCanaDeducoesSafraVO.pas',
  NfeCanaFornecimentoDiarioVO in '..\Comum\VO\NfeCanaFornecimentoDiarioVO.pas',
  NfeCanaVO in '..\Comum\VO\NfeCanaVO.pas',
  NfeCteReferenciadoVO in '..\Comum\VO\NfeCteReferenciadoVO.pas',
  NfeCupomFiscalReferenciadoVO in '..\Comum\VO\NfeCupomFiscalReferenciadoVO.pas',
  NfeDeclaracaoImportacaoVO in '..\Comum\VO\NfeDeclaracaoImportacaoVO.pas',
  NfeDestinatarioVO in '..\Comum\VO\NfeDestinatarioVO.pas',
  NfeDetalheImpostoCofinsVO in '..\Comum\VO\NfeDetalheImpostoCofinsVO.pas',
  NfeDetalheImpostoIcmsVO in '..\Comum\VO\NfeDetalheImpostoIcmsVO.pas',
  NfeDetalheImpostoIiVO in '..\Comum\VO\NfeDetalheImpostoIiVO.pas',
  NfeDetalheImpostoIpiVO in '..\Comum\VO\NfeDetalheImpostoIpiVO.pas',
  NfeDetalheImpostoIssqnVO in '..\Comum\VO\NfeDetalheImpostoIssqnVO.pas',
  NfeDetalheImpostoPisVO in '..\Comum\VO\NfeDetalheImpostoPisVO.pas',
  NfeDetalheVO in '..\Comum\VO\NfeDetalheVO.pas',
  NfeDetEspecificoArmamentoVO in '..\Comum\VO\NfeDetEspecificoArmamentoVO.pas',
  NfeDetEspecificoCombustivelVO in '..\Comum\VO\NfeDetEspecificoCombustivelVO.pas',
  NfeDetEspecificoMedicamentoVO in '..\Comum\VO\NfeDetEspecificoMedicamentoVO.pas',
  NfeDetEspecificoVeiculoVO in '..\Comum\VO\NfeDetEspecificoVeiculoVO.pas',
  NfeDuplicataVO in '..\Comum\VO\NfeDuplicataVO.pas',
  NfeEmitenteVO in '..\Comum\VO\NfeEmitenteVO.pas',
  NfeFaturaVO in '..\Comum\VO\NfeFaturaVO.pas',
  NfeImportacaoDetalheVO in '..\Comum\VO\NfeImportacaoDetalheVO.pas',
  NfeLocalEntregaVO in '..\Comum\VO\NfeLocalEntregaVO.pas',
  NfeLocalRetiradaVO in '..\Comum\VO\NfeLocalRetiradaVO.pas',
  NfeNfReferenciadaVO in '..\Comum\VO\NfeNfReferenciadaVO.pas',
  NfeProcessoReferenciadoVO in '..\Comum\VO\NfeProcessoReferenciadoVO.pas',
  NfeProdRuralReferenciadaVO in '..\Comum\VO\NfeProdRuralReferenciadaVO.pas',
  NfeReferenciadaVO in '..\Comum\VO\NfeReferenciadaVO.pas',
  NfeTransporteReboqueVO in '..\Comum\VO\NfeTransporteReboqueVO.pas',
  NfeTransporteVO in '..\Comum\VO\NfeTransporteVO.pas',
  NfeTransporteVolumeLacreVO in '..\Comum\VO\NfeTransporteVolumeLacreVO.pas',
  NivelFormacaoVO in '..\Comum\VO\NivelFormacaoVO.pas',
  NfeConfiguracaoVO in '..\Comum\VO\NfeConfiguracaoVO.pas',
  NcmVO in '..\Comum\VO\NcmVO.pas',
  NfeNumeroVO in '..\Comum\VO\NfeNumeroVO.pas',
  TributOperacaoFiscalVO in '..\Comum\VO\TributOperacaoFiscalVO.pas',
  CfopVO in '..\Comum\VO\CfopVO.pas',
  ViewTributacaoCofinsVO in '..\Comum\VO\ViewTributacaoCofinsVO.pas',
  ViewTributacaoIcmsVO in '..\Comum\VO\ViewTributacaoIcmsVO.pas',
  ViewTributacaoIpiVO in '..\Comum\VO\ViewTributacaoIpiVO.pas',
  ViewTributacaoIssVO in '..\Comum\VO\ViewTributacaoIssVO.pas',
  ViewTributacaoPisVO in '..\Comum\VO\ViewTributacaoPisVO.pas',
  TributIcmsCustomDetVO in '..\Comum\VO\TributIcmsCustomDetVO.pas',
  TributIcmsCustomCabVO in '..\Comum\VO\TributIcmsCustomCabVO.pas',
  ViewTributacaoIcmsCustomVO in '..\Comum\VO\ViewTributacaoIcmsCustomVO.pas',
  VendedorVO in '..\Comum\VO\VendedorVO.pas',
  VendaCabecalhoVO in '..\Comum\VO\VendaCabecalhoVO.pas',
  VendaDetalheVO in '..\Comum\VO\VendaDetalheVO.pas',
  EstadoCivilVO in '..\Comum\VO\EstadoCivilVO.pas',
  AlmoxarifadoController in '..\Comum\Controller\AlmoxarifadoController.pas',
  EstadoCivilController in '..\Comum\Controller\EstadoCivilController.pas',
  NcmController in '..\Comum\Controller\NcmController.pas',
  NFeCalculoController in '..\Comum\Controller\NFeCalculoController.pas',
  NfeConfiguracaoController in '..\Comum\Controller\NfeConfiguracaoController.pas',
  NfeNumeroController in '..\Comum\Controller\NfeNumeroController.pas',
  PessoaController in '..\Comum\Controller\PessoaController.pas',
  ProdutoController in '..\Comum\Controller\ProdutoController.pas',
  ProdutoMarcaController in '..\Comum\Controller\ProdutoMarcaController.pas',
  ProdutoSubGrupoController in '..\Comum\Controller\ProdutoSubGrupoController.pas',
  TributGrupoTributarioController in '..\Comum\Controller\TributGrupoTributarioController.pas',
  TributIcmsCustomCabController in '..\Comum\Controller\TributIcmsCustomCabController.pas',
  TributOperacaoFiscalController in '..\Comum\Controller\TributOperacaoFiscalController.pas',
  UnidadeProdutoController in '..\Comum\Controller\UnidadeProdutoController.pas',
  VendaCabecalhoController in '..\Comum\Controller\VendaCabecalhoController.pas',
  ViewTributacaoCofinsController in '..\Comum\Controller\ViewTributacaoCofinsController.pas',
  ViewTributacaoIcmsController in '..\Comum\Controller\ViewTributacaoIcmsController.pas',
  ViewTributacaoIcmsCustomController in '..\Comum\Controller\ViewTributacaoIcmsCustomController.pas',
  ViewTributacaoIpiController in '..\Comum\Controller\ViewTributacaoIpiController.pas',
  ViewTributacaoIssController in '..\Comum\Controller\ViewTributacaoIssController.pas',
  ViewTributacaoPisController in '..\Comum\Controller\ViewTributacaoPisController.pas',
  ServerContainer in 'ServerContainer.pas' {FServerContainer: TDataModule},
  JSonVO in '..\Comum\VO\JSonVO.pas',
  Conversor in '..\Comum\Conversor.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  EcfE3VO in '..\Comum\VO\EcfE3VO.pas',
  EcfProdutoVO in '..\Comum\VO\EcfProdutoVO.pas',
  PessoaTelefoneVO in '..\Comum\VO\PessoaTelefoneVO.pas',
  PessoaAlteracaoVO in '..\Comum\VO\PessoaAlteracaoVO.pas',
  PessoaEnderecoVO in '..\Comum\VO\PessoaEnderecoVO.pas',
  PessoaContatoVO in '..\Comum\VO\PessoaContatoVO.pas',
  EmpresaTelefoneVO in '..\Comum\VO\EmpresaTelefoneVO.pas',
  EmpresaContatoVO in '..\Comum\VO\EmpresaContatoVO.pas',
  EmpresaEnderecoVO in '..\Comum\VO\EmpresaEnderecoVO.pas',
  ClienteVO in '..\Comum\VO\ClienteVO.pas',
  FornecedorVO in '..\Comum\VO\FornecedorVO.pas',
  NfeAcessoXmlVO in '..\Comum\VO\NfeAcessoXmlVO.pas',
  NfeFormaPagamentoVO in '..\Comum\VO\NfeFormaPagamentoVO.pas',
  NfeExportacaoVO in '..\Comum\VO\NfeExportacaoVO.pas',
  ViewPessoaClienteVO in '..\Comum\VO\ViewPessoaClienteVO.pas',
  ViewPessoaClienteController in '..\Comum\Controller\ViewPessoaClienteController.pas',
  ViewPessoaTransportadoraVO in '..\Comum\VO\ViewPessoaTransportadoraVO.pas',
  ViewPessoaTransportadoraController in '..\Comum\Controller\ViewPessoaTransportadoraController.pas',
  SpedFiscalController in '..\Comum\Controller\SpedFiscalController.pas',
  FiscalApuracaoIcmsVO in '..\Comum\VO\FiscalApuracaoIcmsVO.pas',
  EcfVendaDetalheVO in '..\Comum\VO\EcfVendaDetalheVO.pas',
  EcfVendaCabecalhoVO in '..\Comum\VO\EcfVendaCabecalhoVO.pas',
  EcfR03VO in '..\Comum\VO\EcfR03VO.pas',
  EcfR02VO in '..\Comum\VO\EcfR02VO.pas',
  ViewSpedC490VO in '..\Comum\VO\ViewSpedC490VO.pas',
  ViewSpedC425VO in '..\Comum\VO\ViewSpedC425VO.pas',
  ViewSpedC370VO in '..\Comum\VO\ViewSpedC370VO.pas',
  ViewSpedC390VO in '..\Comum\VO\ViewSpedC390VO.pas',
  ViewSpedC321VO in '..\Comum\VO\ViewSpedC321VO.pas',
  ViewSpedC300VO in '..\Comum\VO\ViewSpedC300VO.pas',
  ViewSpedC190VO in '..\Comum\VO\ViewSpedC190VO.pas',
  ViewSpedNfeDetalheVO in '..\Comum\VO\ViewSpedNfeDetalheVO.pas',
  EcfNotaFiscalCabecalhoVO in '..\Comum\VO\EcfNotaFiscalCabecalhoVO.pas',
  EcfImpressoraVO in '..\Comum\VO\EcfImpressoraVO.pas',
  UnidadeConversaoVO in '..\Comum\VO\UnidadeConversaoVO.pas',
  ProdutoAlteracaoItemVO in '..\Comum\VO\ProdutoAlteracaoItemVO.pas',
  ViewSpedNfeDestinatarioVO in '..\Comum\VO\ViewSpedNfeDestinatarioVO.pas',
  ViewSpedNfeEmitenteVO in '..\Comum\VO\ViewSpedNfeEmitenteVO.pas',
  ViewSpedNfeItemVO in '..\Comum\VO\ViewSpedNfeItemVO.pas',
  ContadorController in '..\Comum\Controller\ContadorController.pas',
  SintegraController in '..\Comum\Controller\SintegraController.pas',
  ViewSintegra61rVO in '..\Comum\VO\ViewSintegra61rVO.pas',
  ViewSintegra60rVO in '..\Comum\VO\ViewSintegra60rVO.pas',
  ViewSintegra60dVO in '..\Comum\VO\ViewSintegra60dVO.pas',
  EcfSintegra60mVO in '..\Comum\VO\EcfSintegra60mVO.pas',
  EcfSintegra60aVO in '..\Comum\VO\EcfSintegra60aVO.pas',
  DavDetalheAlteracaoVO in '..\Comum\VO\DavDetalheAlteracaoVO.pas',
  DavDetalheVO in '..\Comum\VO\DavDetalheVO.pas',
  DavCabecalhoVO in '..\Comum\VO\DavCabecalhoVO.pas',
  PreVendaDetalheVO in '..\Comum\VO\PreVendaDetalheVO.pas',
  PreVendaCabecalhoVO in '..\Comum\VO\PreVendaCabecalhoVO.pas',
  PreVendaController in '..\Comum\Controller\PreVendaController.pas',
  PreVendaDetalheController in '..\Comum\Controller\PreVendaDetalheController.pas',
  DAVController in '..\Comum\Controller\DAVController.pas',
  DavDetalheController in '..\Comum\Controller\DavDetalheController.pas',
  NfeCabecalhoVO in '..\Comum\VO\NfeCabecalhoVO.pas',
  SetorVO in '..\Comum\VO\SetorVO.pas',
  EmpresaVO in '..\Comum\VO\EmpresaVO.pas',
  FiscalNotaFiscalEntradaVO in '..\Comum\VO\FiscalNotaFiscalEntradaVO.pas',
  ViewPessoaFornecedorVO in '..\Comum\VO\ViewPessoaFornecedorVO.pas',
  TributIcmsUfVO in '..\Comum\VO\TributIcmsUfVO.pas',
  TributConfiguraOfGtVO in '..\Comum\VO\TributConfiguraOfGtVO.pas',
  TributCofinsCodApuracaoVO in '..\Comum\VO\TributCofinsCodApuracaoVO.pas',
  TributIpiDipiVO in '..\Comum\VO\TributIpiDipiVO.pas',
  TipoReceitaDipiVO in '..\Comum\VO\TipoReceitaDipiVO.pas',
  CstIpiVO in '..\Comum\VO\CstIpiVO.pas',
  TributPisCodApuracaoVO in '..\Comum\VO\TributPisCodApuracaoVO.pas',
  CstCofinsVO in '..\Comum\VO\CstCofinsVO.pas',
  EfdTabela435VO in '..\Comum\VO\EfdTabela435VO.pas',
  CstPisVO in '..\Comum\VO\CstPisVO.pas',
  NfeCabecalhoController in '..\Comum\Controller\NfeCabecalhoController.pas',
  ControleEstoqueController in '..\Comum\Controller\ControleEstoqueController.pas',
  ViewPessoaFornecedorController in '..\Comum\Controller\ViewPessoaFornecedorController.pas',
  TributConfiguraOfGtController in '..\Comum\Controller\TributConfiguraOfGtController.pas',
  TipoReceitaDipiController in '..\Comum\Controller\TipoReceitaDipiController.pas',
  CstIpiController in '..\Comum\Controller\CstIpiController.pas',
  CstCofinsController in '..\Comum\Controller\CstCofinsController.pas',
  EfdTabela435Controller in '..\Comum\Controller\EfdTabela435Controller.pas',
  CstPisController in '..\Comum\Controller\CstPisController.pas';

{$R *.res}
{$R T2TiERP_PadraoEmpresa.RES}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFSA, FSA);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.CreateForm(TFServerContainer, FServerContainer);
  Application.Run;
end.
